Added goodpractice and lintr to checks in workflow
jhollway/qDatr pull request #34
Opened 2020-09-24 15:17 UTC by henriquesposito

# Added goodpractice and lintr to checks in workflow

These packages were added as checks were added to workflows to avoid including too many dependencies in the package. 

Closes #18 

# Checklist:

- [ ] I have commented my code in-line, particularly in hard-to-understand areas
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [ ] The package builds on my OS without issues
- [ ] My changes generate no new warnings
- [ ] PR checks all pass for latest commit
- [ ] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [ ] I have updated NEWS.md
- [ ] I have given this pull request an informative title and description

2020-09-24 15:31 UTC, henriquesposito commented
It appears that the issue is when trying to save the goodpractice cp check results. For more or less similar issues see here https://github.community/t/downloading-workflows-checkout-v1-fails-and-fails-the-build/17091 and here https://stackoverflow.com/questions/62126024/github-actions-error-an-action-could-not-be-found. We could erase the save part and see if we can first run goodpractice as a check and then try and save results?

2020-09-25 11:09 UTC, jhollway commented
/style

2020-09-25 11:13 UTC, jhollway commented
/document

2020-09-25 11:40 UTC, jhollway requested changes

2020-09-25 11:40 UTC, jhollway commented on R/standardise.R
>                            paste0("(?<!\\w)", ords,"(?!\\w)"),
Add space after commas

2020-09-25 11:40 UTC, jhollway commented on tests/testthat/test_rearrange.R
> +context("rearrange")
No need for context() calls in testthat anymore

2020-09-25 11:40 UTC, jhollway commented on tests/testthat/test_reunite.R
> +context("reunite")
No need for context() calls in testthat anymore

2020-09-25 11:40 UTC, jhollway commented on .github/workflows/prcommands.yml
> +on:
Doesn't seem to be triggered correctly. Please investigate.

2020-09-25 11:40 UTC, jhollway commented on R/standardise.R
>                            paste0("(?<!\\w)", as.roman(1:100),"(?!\\w)"),
Add space after commas

2020-09-25 11:40 UTC, jhollway commented on R/standardise.R
>                            paste0("(?<!\\w)", as.roman(1:100),"(?!\\w)"),
Also, need space around operators (e.g. "=" or "==")

2020-09-25 11:40 UTC, jhollway commented on tests/testthat/test_rearrange.R
> +context("rearrange")
context() no longer needed with testthat

2020-09-25 11:40 UTC, jhollway commented on tests/testthat/test_reunite.R
> +context("reunite")
context() no longer needed with testthat

2020-09-25 11:40 UTC, jhollway commented on R/wrangling.R
> +#' @param ba Optional string identifying reference variable
Change parameter name to something more indicative than 'ba'

2020-09-25 12:11 UTC, jhollway commented on .github/workflows/prcommands.yml
> +on:
As an alternative, see also https://github.com/r-hub/pkgsearch/blob/master/.github/workflows/pr-label-commands.yml which runs on PR labelling rather than comment body triggering

2020-09-25 12:13 UTC, jhollway commented on .github/workflows/prcommands.yml
> +on:
Another alternative is to make these precommit hooks: https://lorenzwalthert.github.io/precommit/

2020-09-25 12:47 UTC, henriquesposito commented on .github/workflows/prcommands.yml
> +on:
I did not find out why was this was triggered...

2020-09-25 13:20 UTC, henriquesposito commented on .github/workflows/prcommands.yml
> +on:
We could use the solution of running on PR labelling rather than comment body triggering and see if the warning goes away, but I still would not know what the warning is about to begin with.

2020-09-25 13:40 UTC, jhollway requested changes

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +                           {
Opening curly braces should never go on their own line and should always be followed by a new line.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +                             s <- substring(s, 2); if (strict) tolower(s) else s},
Lines should not be more than 80 characters.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +                         paste0("|", gsub(" ", "-", as.character(ords))),
Trailing whitespace is superfluous.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +  out <- textclean::mgsub(out,
Trailing whitespace is superfluous.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +                          paste0("(?<!\\w)", ords, "(?!\\w)"),
Trailing whitespace is superfluous.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
> +                          as.numeric(1:100),
Trailing whitespace is superfluous.

2020-09-25 13:40 UTC, jhollway commented on R/standardise.R
>                            safe = TRUE, perl = TRUE, ignore.case = TRUE, fixed = FALSE)
Lines should not be more than 80 characters.

2020-09-25 13:40 UTC, jhollway commented on R/wrangling.R
> +#' @param refva Optional string identifying reference variable
Great! Still, most code uses 'var' to abbreviate variable, not 'va', and I think anyway just 'ref' might be enough (and clearer to read).

2020-09-25 13:40 UTC, jhollway commented on tests/testthat/test_rearrange.R
> -  expect_error(rearrange(data, "letters", "before"), "must specify ba column")
Excellent, but would also need to be updated if name change

2020-09-25 13:40 UTC, jhollway commented on tests/testthat/test_reunite.R
>  data <- data.frame(fir=c(NA, "two", "three", NA),
Excellent!

2020-09-25 13:41 UTC, jhollway commented
Also, I wonder whether you can set lintr or goodpractice (whichever is annotating the code I review) to only run on Mac (and not ubuntu) -- otherwise I'm getting duplicated annotations everywhere.

2020-09-28 08:40 UTC, jhollway commented
/document

2020-09-28 08:43 UTC, jhollway approved these changes

2020-09-28 09:02 UTC, merged