Added resequence(), recollect() and qpackage() functions
jhollway/qDatr pull request #41
Opened 2020-09-28 12:19 UTC by henriquesposito

# The resequence(), recollect() and qpackage() functions were added. 

Closes #23  #30  #25 

# Checklist:

- [ ] I have commented my code in-line, particularly in hard-to-understand areas
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [ ] The package builds on my OS without issues
- [ ] My changes generate no new warnings
- [ ] PR checks all pass for latest commit
- [ ] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [ ] I have updated NEWS.md
- [ ] I have given this pull request an informative title and description

2020-09-28 14:35 UTC, henriquesposito commented
The error I get when running 'devtools::check' in my computer is: " Namespace dependency not required: 'usethis' ".  The package 'usethis' is listed as a dependency under namespace and not in the description file or anywhere else in the package that I can find. Why is this happening?

2020-09-28 15:01 UTC, jhollway commented
We will be using `usethis` for this function, but it is not yet written into the function. You can comment out the @import line from the R script for now, which should remove it from NAMESPACE when you rerun documentation.

> On 28 Sep 2020, at 16:35, Henrique Sposito <notifications@github.com> wrote:
> 
> ﻿
> The error I get when running 'devtools::check' in my computer is: " Namespace dependency not required: 'usethis' ". The package 'usethis' is listed as a dependency under namespace and not in the description file or anywhere else in the package that I can find. Why is this happening?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-02 15:32 UTC, jhollway requested changes

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +#' @param packageName A string giving the desired name of the package, must start with "q"
Line over 80 characters

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +#' @param packageAuthor A string, list or vector giving the package author(s), required
Line over 80 characters

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +#' @param update A logical indicating whether existing files should be overwritten, by default TRUE.
Line over 80 characters

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +#' @details The function establishes many of the required files and folder structures
Line over 80 characters

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +#' @return A new package structure
Remove trailing whitespace

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +                            update = TRUE){
Add space between right parenthesis and opening curly brace

2020-10-02 15:32 UTC, jhollway commented on R/package.R
> +  if(is.null(packageAuthor)) stop("Please declare at least one author")
Cover these lines with tests

2020-10-02 15:32 UTC, jhollway commented on R/standardise.R
> +      if (sum((!grepl("-01-01", dates))*1)>=len) dates <- dates[!grepl("-01-01",dates)]
Line not covered by tests?

2020-10-02 16:40 UTC, jhollway approved these changes
Looks good, thanks @henriquesposito

2020-10-02 16:40 UTC, merged